export const initialProducts = [
  { id: 1, name: "كمون", pricePerKg: 240 },
  { id: 2, name: "فلفل اسود", pricePerKg: 360 },
  { id: 3, name: "بهارات 7", pricePerKg: 320 },
  { id: 4, name: "شطه", pricePerKg: 100 },
  { id: 5, name: "كركم", pricePerKg: 160 },
  { id: 6, name: "كاري", pricePerKg: 60 },
  { id: 7, name: "قرفه", pricePerKg: 160 },
  { id: 8, name: "زنجبيل", pricePerKg: 240 },
  { id: 9, name: "زعتر", pricePerKg: 60 },
  { id: 10, name: "روز ماري", pricePerKg: 80 },
  { id: 11, name: "كزبره", pricePerKg: 80 },
  { id: 12, name: "بابريكا", pricePerKg: 140 },
  { id: 13, name: "بصل بودر", pricePerKg: 120 },
  { id: 14, name: "ثوم بودر", pricePerKg: 120 },
  { id: 15, name: "لورا ورق", pricePerKg: 120 },
  { id: 16, name: "حبهان", pricePerKg: 1500 },
  { id: 17, name: "بهارات حووشي", pricePerKg: 160 },
  { id: 18, name: "بهارات محشي", pricePerKg: 160 },
  { id: 19, name: "بهارات الكبده", pricePerKg: 160 },
  { id: 20, name: "بهارات السمك والجمبري", pricePerKg: 160 },
  { id: 21, name: "بهارات الشيش طاووق", pricePerKg: 160 },
  { id: 22, name: "مرقه دجاج", pricePerKg: 120 },
  { id: 23, name: "مرقه لحمه", pricePerKg: 120 },
  { id: 24, name: "بهارات شاورما لحمه", pricePerKg: 160 },
  { id: 25, name: "بهارات شاورما فراخ", pricePerKg: 160 },
  { id: 26, name: "توابل البطاطس", pricePerKg: 160 },
  { id: 27, name: "توابل البرجر", pricePerKg: 160 },
  { id: 28, name: "بهارات الكبسه", pricePerKg: 160 },
  { id: 29, name: "كمون ناعم", pricePerKg: 320 },
  { id: 30, name: "كزبره ناعمه", pricePerKg: 141 },
  { id: 31, name: "كركم هندي", pricePerKg: 180 },
  { id: 32, name: "كاري هندي", pricePerKg: 150 },
  { id: 33, name: "بابريكا صيني", pricePerKg: 190 },
  { id: 34, name: "شطه سوداني", pricePerKg: 240 },
  { id: 35, name: "لوري نمره بالت", pricePerKg: 194 },
  { id: 36, name: "ثوم بودر درجه اولي", pricePerKg: 100 },
  { id: 37, name: "بصل بودر درجه اولي", pricePerKg: 100 },
  { id: 38, name: "روز ماري", pricePerKg: 195 },
  { id: 39, name: "زعتر بلدي", pricePerKg: 180 },
  { id: 40, name: "سبع بهارات سوبر", pricePerKg: 280 },
  { id: 41, name: "كربونات تركي", pricePerKg: 138 },
  { id: 42, name: "ملح صيني", pricePerKg: 165 },
  { id: 43, name: "ملح ليمون", pricePerKg: 245 },
  { id: 44, name: "مرقه", pricePerKg: 160 },
  { id: 45, name: "ليمون اسود", pricePerKg: 56 },
  { id: 46, name: "فلفل فيتنامي حصي للطحن", pricePerKg: 560 },
  { id: 47, name: "حنزبيل ناعم", pricePerKg: 370 },
  { id: 48, name: "قرفه ناعمه", pricePerKg: 100 },
];
